### ISSUE TITLE
Array as ViewModel

### ISSUE THREAD

**Issue by tbreuss** [templado/documentation#2]
The documentation doesn't say if arrays are supported as "ViewModels" or I haven't found the place yet.

So I wonder if arrays are supported, as I think most users are used to using arrays in this context.

**Comment by theseer** [comment]
The term `array` isn't specific enough to provide a straight yes or no answer. That's because PHP doesn't unfortunately differentiate between lists and dictionary types.

Templado sees arrays as lists or, to be specific, treats everything that is `iterable` as a list, ignoring potential other properties available.

So to answer your question based on what you most likely asked: no, __associative__ arrays are not supported. 
A simple workaround would be to provide wrapper class that implements `__call` to map the request to the respective array key. With Templado 5, one can also use `StdClass` or a class with public properties as an alternative to achieve the same. 

I'll add a clarifying paragraph to the docs for Templado 5.0, which i'm currently working on.

**Comment by tbreuss** [comment]
Thank you for the clarification. It also answers my vague question well.
